version: '3.8'

services:
  catalog_db:
    image: postgres:15
    container_name: catalog_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - catalog_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  catalog_service:
    build:
      context: catalog_service
      dockerfile: Dockerfile
    container_name: catalog_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@catalog_db:5432/${POSTGRES_DB}
    depends_on:
      catalog_db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./catalog_service:/catalog_service


  order_db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  order_service:
    build:
      context: order_service
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8001:8001"
    environment:
      CATALOG_URL: http://catalog_service:8000
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@order_db:5432/${POSTGRES_DB}
    depends_on:
      order_db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./order_service:/order_service

networks:
  app-network:
    driver: bridge

volumes:
  catalog_data:
  order_data: